apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hyperspace-operations-and-transport
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/gsigmund/open-ecosystem-challenges.git
        revision: hotrod
        directories:
          - path: adventures/01-echoes-lost-in-orbit/expert/manifests/*
          - path: adventures/01-echoes-lost-in-orbit/expert/manifests/appset.yaml # Ignore this file itself
            exclude: true
  template:
    metadata:
      name: '{{ path.basename }}'
      labels:
        app.kubernetes.io/managed-by: argocd
    spec:
      project: default
      source:
        repoURL: https://github.com/gsigmund/open-ecosystem-challenges.git
        targetRevision: hotrod
        path: '{{ path }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ path.basename }}'
      syncPolicy:
        automated:
          enabled: true
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

